source 'https://rubygems.org'
ruby '2.5.1'
gem 'activesupport'
gem 'addressable'
gem 'bundler'
gem 'feedlr'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'httparty'
gem 'rake'
gem 'rubocop'
